name: spot-it
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - altair=6.0.0=pyhd8ed1ab_1
  - attrs=25.4.0=pyhcf101f3_1
  - aws-c-auth=0.9.3=h1ddaa69_0
  - aws-c-cal=0.9.13=h6ee9776_1
  - aws-c-common=0.12.6=hc919400_0
  - aws-c-compression=0.3.1=h16f91aa_9
  - aws-c-event-stream=0.5.7=h9ae9c55_1
  - aws-c-http=0.10.7=h5928ca5_5
  - aws-c-io=0.23.3=hbe03c90_5
  - aws-c-mqtt=0.13.3=haf5c5c8_11
  - aws-c-s3=0.11.3=h8da9771_1
  - aws-c-sdkutils=0.2.4=h16f91aa_4
  - aws-checksums=0.2.7=h16f91aa_5
  - aws-crt-cpp=0.35.4=h74951b9_0
  - aws-sdk-cpp=1.11.606=h4e1b0f7_10
  - azure-core-cpp=1.16.1=h88fedcc_0
  - azure-identity-cpp=1.13.2=h853621b_1
  - azure-storage-blobs-cpp=12.15.0=h10d327b_1
  - azure-storage-common-cpp=12.11.0=h7e4aa5d_1
  - azure-storage-files-datalake-cpp=12.13.0=hb288d13_1
  - backports.zstd=1.2.0=py314h680f03e_0
  - blinker=1.9.0=pyhff2d567_0
  - brotli-python=1.2.0=py314h3daef5d_1
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.6=hc919400_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cachetools=6.2.4=pyhd8ed1ab_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh8f84b5b_1
  - gflags=2.2.2=hf9b8971_1005
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.45=pyhff2d567_0
  - glog=0.7.1=heb240a5_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - jinja2=3.1.6=pyhcf101f3_1
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - krb5=1.21.3=h237132a_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250512.1=cxx17_hd41c47c_0
  - libarrow=22.0.0=he6e817a_6_cpu
  - libarrow-acero=22.0.0=hc317990_6_cpu
  - libarrow-compute=22.0.0=h75845d1_6_cpu
  - libarrow-dataset=22.0.0=hc317990_6_cpu
  - libarrow-substrait=22.0.0=h144af7f_6_cpu
  - libblas=3.11.0=5_h51639a9_openblas
  - libbrotlicommon=1.2.0=hc919400_1
  - libbrotlidec=1.2.0=hc919400_1
  - libbrotlienc=1.2.0=hc919400_1
  - libcblas=3.11.0=5_hb0561ab_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.17.0=hdece5d2_1
  - libcxx=21.1.7=hf598326_0
  - libdeflate=1.25=hc11a715_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=he5f378a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgcc=15.2.0=hcbb3090_16
  - libgfortran=15.2.0=h07b0088_16
  - libgfortran5=15.2.0=hdae7583_16
  - libgoogle-cloud=2.39.0=head0a95_0
  - libgoogle-cloud-storage=2.39.0=hfa3a374_0
  - libgrpc=1.73.1=h3063b79_1
  - libiconv=1.18=h23cfdf5_2
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.11.0=5_hd9741b5_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libmpdec=4.0.0=h5505292_0
  - libnghttp2=1.67.0=hc438710_0
  - libopenblas=0.3.30=openmp_ha158390_3
  - libopentelemetry-cpp=1.21.0=he15edb5_1
  - libopentelemetry-cpp-headers=1.21.0=hce30654_1
  - libparquet=22.0.0=h0ac143b_6_cpu
  - libpng=1.6.53=hfab5511_0
  - libprotobuf=6.31.1=h658db43_2
  - libre2-11=2025.11.05=h91c62da_0
  - libsqlite=3.51.1=h9a5124b_0
  - libssh2=1.11.1=h1590b86_0
  - libthrift=0.22.0=h14a376c_1
  - libtiff=4.7.1=h4030677_1
  - libutf8proc=2.11.2=hd2415e0_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.15.1=hba2cd1d_0
  - libxml2-16=2.15.1=h8eac4d7_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.7=h4a912ad_0
  - lz4-c=1.10.0=h286801f_1
  - markupsafe=3.0.3=pyh7db6752_0
  - narwhals=2.14.0=pyhcf101f3_0
  - ncurses=6.5=h5e97a16_3
  - nlohmann_json=3.12.0=h248ca61_1
  - numpy=2.3.5=py314h5b5928d_0
  - openjpeg=2.5.4=hbfb3c88_0
  - openssl=3.6.0=h5503f6c_0
  - orc=2.2.1=h4fd0076_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py314ha3d490a_2
  - pillow=12.0.0=py314h57fbdfe_2
  - pip=25.3=pyh145f28c_0
  - prometheus-cpp=1.3.0=h0967b3e_0
  - protobuf=6.31.1=py314hc77ea51_2
  - pthread-stubs=0.4=hd74edd7_1002
  - pyarrow=22.0.0=py314he55896b_0
  - pyarrow-core=22.0.0=py314hf20a12a_0_cpu
  - pydeck=0.9.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.14.2=h40d2674_100_cp314
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.14=8_cp314
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=pyh7db6752_0
  - re2=2025.11.05=h64b956e_0
  - readline=8.3=h46df422_0
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rpds-py=0.30.0=py314haad56a0_0
  - six=1.17.0=pyhe01879c_1
  - smmap=5.0.2=pyhd8ed1ab_0
  - snappy=1.2.2=hada39a4_1
  - streamlit=1.52.1=pyhd8ed1ab_0
  - tenacity=9.1.2=pyhd8ed1ab_0
  - tk=8.6.13=h892fb3f_3
  - toml=0.10.2=pyhcf101f3_3
  - tornado=6.5.4=py314h0612a62_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=h8577fbf_0
  - urllib3=2.6.2=pyhd8ed1ab_0
  - watchdog=6.0.0=py314h0612a62_2
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - yaml=0.2.5=h925e9cb_3
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=h8359307_2
  - zlib-ng=2.3.2=h248ca61_0
  - zstd=1.5.7=hbf9d68e_6
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/spot-it
